name: Release

on:
    push:
      tags:
        - 'v*'

jobs:
    clojars:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: clojars-deploy
              uses: "DeLaGuardo/setup-clojure@12.5"
              with:
                cli: "1.11.1.1139"
            - run: |
                clj -M:dev --report stderr -m com.moclojer.tools.build && \
                clj -X:deploy-clojars
              env:
                CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
                CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
